### ISSUE TITLE
Перестает работать перевод после многих переводов за ед. времени

### ISSUE THREAD

**Issue by hw0aran9** [jarni-ua/OP2Translator#1]
Полагаю, дело в ограничениях API? (смена IP не помогает, видимо отслеживают иначе) 
В коде используется, кажется, что-то отличное от того, что описано в документации к API, просто обращение по ссылке. 
Было бы неплохо переключить на метод, описанный в документации. Возможно, это решит проблему. 
https://cloud.google.com/translate/docs/reference/libraries#client-libraries-usage-csharp

**Comment by jarni-ua** [comment]
Именно так, поскольку используется "тестовый" способ. Использовать официальный интерфейс было бы очень удобно, но он платный. Переход на платную версию мне кажется нецелесообразным потому что перевод это одноразовая вещь, да и "блок" действует всего 1 день и у меня случался всего раза 3 за последние 2 года.

**Comment by hw0aran9** [comment]
Так и понял. Смена IP все-таки помогает, несмотря на сказанное ранее. Сейчас перевожу файл с фамилиями, а это много коротких строк и обращений к API. VPN наше все.
